/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import java.awt.Toolkit;

/**
 *
 * @author daisy
 */
public class ClassSelectionScreen extends javax.swing.JFrame {

    
    Toolkit tk = Toolkit.getDefaultToolkit();
    public static int CharacterClass;
    
    public ClassSelectionScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WarriorButton = new javax.swing.JButton();
        MageButton = new javax.swing.JButton();
        AssassinButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        WarriorButton.setBorderPainted(false);
        WarriorButton.setContentAreaFilled(false);
        WarriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarriorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(WarriorButton);
        WarriorButton.setBounds(100, 910, 370, 140);

        MageButton.setBorderPainted(false);
        MageButton.setContentAreaFilled(false);
        MageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MageButton);
        MageButton.setBounds(750, 910, 380, 140);

        AssassinButton.setBorderPainted(false);
        AssassinButton.setContentAreaFilled(false);
        AssassinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssassinButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AssassinButton);
        AssassinButton.setBounds(1370, 910, 370, 140);

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(40, 40, 230, 100);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Class Selection Screen.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1930, 1100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
        GUIs.NicknameChoosingScreen nicknameChoosing = new GUIs.NicknameChoosingScreen();
            
            int WidthSize = (int) tk.getScreenSize().getWidth();
            int HeightSize = (int) tk.getScreenSize().getHeight();
            
            nicknameChoosing.setSize(WidthSize, HeightSize);
            nicknameChoosing.setVisible(true);
            this.dispose();
        
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void WarriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarriorButtonActionPerformed
        
        GUIs.WarriorClassScreen warrior = new GUIs.WarriorClassScreen();
            
            int WidthSize = (int) tk.getScreenSize().getWidth();
            int HeightSize = (int) tk.getScreenSize().getHeight();
            
            warrior.setSize(WidthSize, HeightSize);
            warrior.setVisible(true);
            this.dispose();
        
        
        
    }//GEN-LAST:event_WarriorButtonActionPerformed

    private void MageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MageButtonActionPerformed
        
        GUIs.MageClassScreen mage = new GUIs.MageClassScreen();
            
            int WidthSize = (int) tk.getScreenSize().getWidth();
            int HeightSize = (int) tk.getScreenSize().getHeight();
            
            mage.setSize(WidthSize, HeightSize);
            mage.setVisible(true);
            this.dispose();
        
        
        
    }//GEN-LAST:event_MageButtonActionPerformed

    private void AssassinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssassinButtonActionPerformed
        
        GUIs.AssassinClassScreen assassin = new GUIs.AssassinClassScreen();
            
            int WidthSize = (int) tk.getScreenSize().getWidth();
            int HeightSize = (int) tk.getScreenSize().getHeight();
            
            assassin.setSize(WidthSize, HeightSize);
            assassin.setVisible(true);
            this.dispose();
        
        
        
    }//GEN-LAST:event_AssassinButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassSelectionScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssassinButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Background;
    private javax.swing.JButton MageButton;
    private javax.swing.JButton WarriorButton;
    // End of variables declaration//GEN-END:variables
}
